config/routes.rb
Rails.application.routes.draw do
  get 'home/checkr'

  root 'home#sparks'

  get 'home/flynn'

  get 'home/sparks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def checkr
  end

  def flynn
  end

  def sparks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/flynn.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-e85183a3.png">
  <link rel="icon" type="image/png" href="/images/favicon-32x32-86f78ec8.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/images/favicon-16x16-667a7d8e.png" sizes="16x16">
  <link rel="shortcut icon" href="/images/favicon.ico">

  <link href="/blog.xml" rel="alternate" title="Atom feed" type="application/atom+xml" />

  <title>Flynn – The product that ops provides to developers</title>

  

  
</head>

<body>
<section class = "flynn">
<div id="First_part">
  <nav class="mnav">
  <ul id="list1">
    <li class="brand">
      <a href="/">
        <%= image_tag("Flynn.png", :alt => "flynn", size: "90x37") %>
      </a>
    </li>

	<div id="list_items">
	    <li class="item ">
	      <a href="/about">About</a>
	    </li>

	    <li class="item ">
	      <a href="/docs">Docs</a>
	    </li>

	    <li class="item ">
	      <a href="/blog">Blog</a>
	    </li>

	    <li class="item ">
	      <a href="/pricing">Pricing</a>
	    </li>

	    <li class="btn">
	      <a href="/docs/installation">Try</a>
	    </li>
	</div>
	 
  </ul>
</nav>


  <section class="content-container header index" id="demo">

    <h1>
      Throw away the duct tape. <br />
      Say hello to
      <span class="flynn">Flynn</span>.
    </h1>


 
  <video class="video-js" controls>
    <source src="https://dl.flynn.io/assets/flynn_demo_2m.mp4" type="video/mp4">
  </video>
  </section>

<nav class="hnav">
  <ul id="list2">
    <li class="list3">
      <a href="/apps">Apps</a>
    </li>

    <li class="list3">
      <a href="/manage">Manage</a>
    </li>

    <li class="list3">
      <a href="/databases">Databases</a>
    </li>
  </ul>
</nav>
</div>
<div id="central-text">
<section class="content-container narrow-centered">
  <header>
    <h2>Powerful and easy. The way it should be.</h2>
  </header>
<div class="h4">
  <h4>
    Flynn is an open source platform (PaaS) for running applications in production.
  </h4>
  <p>It does everything you need, out of the box:</p>
</div>
  <div class="content">
    <ul id="exception">
      <li>Creates running <a href="/apps">applications</a> directly from your code so there's no need to learn configuration management or build custom stacks for each app</li>
      <li>Routes and load balances traffic to every instance of each of your apps</li>
      <li>Includes built-in Postgres, MySQL, and MongoDB <a href="/databases">databases</a> with safe, automatic high availability</li>
      <li>Connects all your microservices with built-in service discovery</li>
      <li>Makes <a href="/manage">scaling</a> your cluster to just the right size easy so you save money on your cloud bills</li>
      <br>
    </ul>
  </div>
</section>

<section class="centered">
  <a href="/docs/installation" class="try-now-btn">
    Try Flynn Now
  </a>
</section>

<section class="content-container narrow-centered header-only">
  <article>
    <header>
      <h2>Whatever you need,<br/> Flynn can help.</h2>
    </header>
  </article>
</section>

<section class="content-container stacked narrow-centered">
  <article>
    <header>
      <h3>Getting apps running in the cloud <br/>is way too hard.</h3>
    </header>
	<div id="paragraph">
    <p>
      Deployment. Ops. Databases. Containers. Configuration management.
      Service discovery. Forget about all of them.
    </p>

    <p>
      Flynn is all you need to know.
    </p>

    <p>
      Flynn is a simple, turnkey solution to cloud, containers, ops, whatever
      you want to call it. Flynn manages all the technology you need under the
      surface. So you get all the benefits with none of the work or complexity.
    </p>

    <p>
      Get back to writing your app and running your business.
    </p>

    <p>
      And Flynn gets better everyday. We track the infrastructure space closely
      and regularly integrate new components and features, so you get the best
      technology without having to figure out how everything fits together.
    </p>

    <p>
      And like all good things, it's completely free.
    </p>
    </div>
  </article>
</section>

<section class="content-container stacked narrow-centered">
  <article>
    <header>
      <h3>Growth is hard.</h3>
    </header>
	<div id="paragraph">
    <p>
      Users love your product and you're growing like crazy.  Your engineering
      team is already stretched thin keeping up with growth.
    </p>

    <p>
      You're using more cloud instances, apps, containers, languages,
      frameworks, and databases.
    </p>

    <p>
      Your ops team (if you have one) is already under water trying to keep up.
    </p>

    <p>
      Flynn helps you breeze through those challenges.
    </p>

    <p>
      Developers can deploy with a single command straight from git. Operators
      manage a single platform instead of doing custom work before each app can
      be deployed.
    </p>

    <p>
      Databases manage themselves. Service discovery, scheduling, containers,
      routing, and cluster management are all taken care of in the background.
    </p>
	</div>
  </article>
</section>

<section class="content-container stacked narrow-centered">
  <article>
    <header>
      <h3>Your world is changing too quickly.</h3>
    </header>
	<div id="paragraph">
    <p>
      New languages, frameworks, version control systems, databases,
      architectures, and other bleeding-edge technologies are taking over,
      fast.
    </p>

    <p>
      You need containers, microservices, polyglot everything, and cost savings
      yesterday.
    </p>

    <p>
      Developers need the best tools for the job in a changing world. Operators
      and IT teams need a platform they can manage instead of building
      everything from scratch, one piece at a time.
    </p>

    <p>
      Flynn has you covered. All the shiny new best practices in a single
      turnkey solution.
    </p>

    <p>
      It's free and open source so you can have tomorrow's technology today
      without any lock-in.
    </p>
	</div>
  </article>
</section>

<section class="content-container stacked narrow-centered">
  <article>
    <header>
      <h3>We can run it for you.</h3>
    </header>
	<div id="paragraph">
    <p>
    You can run Flynn yourself or our experienced team can install, run, and
    manage a Flynn cluster for you. We work with your developers to help you
    get the most out of Flynn and your apps. And since Flynn is 100% open
    source there's no lock-in.
    </p>

    <p>
    We can also support your ops, IT, or sysadmins team 24/7 if you prefer to
    handle things yourself but still want help on call.
    </p>
	</div>
	</br></br>
  </article>
</section>


  <footer id="footer">
  <section class="content-container">
  	<section class="centered">
    <a href="/docs/installation" class="try-now-btn">
      Try Flynn Now
    </a>
	</section>

    <section class="content-container centered">
      <form action="https://flynn.us7.list-manage.com/subscribe/post?u=9600741fc187618e1baa39a58&id=a2b322e5ab" method="post" target="_blank" novalidate class="mailing-list-form">
  <h2>Mailing List</h2>
  <label id="email">Email Address&nbsp;
    <input id="email_box" type="email" name="EMAIL" placeholder="you@example.com">
  </label>
  <button id="subscribe" type="submit" name="subscribe">Subscribe</button>
</form>
</div>

    </section>
    <br/><br/><br/>

    <nav class="fnav" >
      <ul id="fnav">
        <li>
          <a href="https://github.com/flynn/flynn">Get the source on GitHub.</a>
        </li>

        <li>
          <a href="https://webchat.freenode.net?channels=flynn">Join us on IRC.</a>
        </li>

        <li>
          <a href="https://twitter.com/flynnscale">Follow us on Twitter.</a>
        </li>

        <li>
          <a href="/docs">Read the docs.</a>
        </li>

        <li>
          <a href="https://shop.flynn.io">Get some swag.</a>
        </li>

        <li>
          <a href="mailto:info@flynn.io">Email us.</a>
        </li>
      </ul>
    </nav>
  </section>

  <section class="copyright">
    Flynn is designed, built, and managed by Prime Directive, Inc.<br />
    &copy; 2013-2018 Prime Directive, Inc. Flynn® is a trademark of Prime Directive, Inc.<br />
    <a href="/legal/privacy">Privacy Policy</a> | <a href="/docs/trademark-guidelines">Trademark Guidelines</a>
  </section>
</footer>
</section>
</body>

app/views/home/sparks.html.erb
<h1>Hiii ! </h1>
<h4>Que veux tu voir ?</h4>

<%= link_to "Flynn", home_flynn_path %>
<%= link_to "Checkr", home_checkr_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandingPages</title>
    <%= csrf_meta_tags %>

  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>